// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.7.2.
// **********************************************************************

package com.qq.tars.quickstart.server.testapp;

import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.annotation.*;
import com.qq.tars.common.support.Holder;

@Servant
public interface HelloServant {

	 String hello(@TarsMethodParameter(name="no")int no, @TarsMethodParameter(name="name")String name);

	 int getAllUserInfo(@TarsHolder(name="resp") Holder<java.util.List<User>> resp);

	 java.util.List<User> getAllUserInfoAsReturn();
}
